### ISSUE TITLE
New micro:bit firmware

### ISSUE THREAD

**Issue by jamesadevine** [make4all/sonification#126]
Hi @venkateshpotluri,

We've turned off some of the services exposed by the micro:bit. Hopefully this will put less strain on the software stack!

Let us know!

Peli: removed old outdated binary

**Comment by venkateshpotluri** [comment]
@jamesadevine  I tested the sound level with this firmware and I think the data stops streaming after a few seconds. I tested the same code with the version of the firmware I was using earlier and this does not happen. I tried looking at the logs but there are too many log statements for me to identify a specific cause. Do you have any suggestions for me to send debugging info that would help?

**Comment by jamesadevine** [comment]
CC @pelikhan

**Comment by pelikhan** [comment]
How do I repro this?

**Comment by pelikhan** [comment]
James can you add the makecode project somewhere in the repo?

**Comment by jamesadevine** [comment]
@pelikhan https://github.com/make4all/sonification/commit/11f117b1606d304171d10aaf90b0030e3adbf0ce

**Comment by venkateshpotluri** [comment]
@pelikhan  repro steps:
1. start the development server with yarn start
2. go to localhost:3000/dashboard.
3. connect Micro:Bit with the linked firmware installed, and connect.
4. add a note handler to the sound level.
5. keep making some sounds for a few seconds.
You will notice that the value stops changing after some time (after about 30-60 seconds).

**Comment by pelikhan** [comment]
I've added instructions to rebuild the firmware at https://github.com/make4all/sonification/blob/main/makecode-microbit/README.md

**Comment by pelikhan** [comment]
@venkateshpotluri try again with the new firmware and build of jacdac-ts. I'll leave my device to run overnight to see

**Comment by venkateshpotluri** [comment]
@pelikhan  I tried the following and the issue still persists.

## trial 1
1. installed the makecode project by running `npm install -g makecode`
2. navigated to the makecode-microbit folder.
3. executed `mkc -d`
## trial 2.
steps 1-3 above, and then copied in the firmware linked in this issue.

**Comment by pelikhan** [comment]
The firmware linked is outdated. I have removed it from the comment to avoid any kind of confusion. 
* Make sure to run `npm install -g -u makecode` to update any previously installed version of the command line tool (-u forces the update)

I will try to repro again. Are you connecting any Jacdac devices to your micro:bit?

**Comment by venkateshpotluri** [comment]
I followed the steps you suggested and still run into the same issue. I do not have any jacdac devices connected: I just have the Jacdapter connected to the Micro:bit.

**Comment by venkateshpotluri** [comment]
I tried again with the jacdapter removed and the issue persists.

**Comment by jamesadevine** [comment]
Venkatesh, incase the instructions were unclear, please load the following hex file onto your micro:bit:
[mbcodal-binary.zip](https://github.com/make4all/sonification/files/8333764/mbcodal-binary.zip)

**Comment by venkateshpotluri** [comment]
Peli and I had a debugging meeting, and my understanding is that we were able to resolve this with the latest firmware that Peli shared with me. This issue appears to be resolved, @pelikhan  we can close this if you feel that this is fixed as well.
